A            MAITCL         3          COLHDG('ITEM CLASS')   
A            MAITCD         6  0       COLHDG('ITEM CODE')    
A            MADESC       150          COLHDG('DESCRIPTION')  
A            MALEN          8  0       COLHDG('LENGTH')       
A            MACSCD         6  0       COLHDG('CUSTOMER CODE')
A            MACSNM       100          COLHDG('CUSTOMER NAME')
A            MADOCT         3          COLHDG('DOC TYPE')     
A            MADOCN        10          COLHDG('DOC NO.')      
A            MADODT         8  0       COLHDG('DOC DATE')     
A            MAORDT         8  0       COLHDG('ORDER DATE')   
A            MARQDT         8  0       COLHDG('REQ DATE')     
A            MADLNO         8  0       COLHDG('DELIVERY NO')  
A            MADLDT         8  0       COLHDG('DELIVERY DATE')
A            MAORDT         3          COLHDG('ORDER TYPE')   
A            MAORDN         8  0       COLHDG('ORDER NO')     
A            MAQTY          8  0       COLHDG('QUANTITY')     
A            MAUPRC        10  2       COLHDG('UNIT PRICE')   
A            MAAMT         16  2       COLHDG('AMOUNT')       
A            MAPROF        16  2       COLHDG('PROFIT')       
A            MAUCST        16  2       COLHDG('UNIT COST')    
A            MATCST        16  2       COLHDG('TOTAL COST')   
A            MAWGHT        16  3       COLHDG('WEIGHT')       
A            MATWGH        16  3       COLHDG('TOTAL WEIGHT') 
A            MAPCEX         6  2       COLHDG('PERCENT EXP')  
A            MACSTP         8  0       COLHDG('CUSTOMER TYPE')
A            MARGN          2          COLHDG('REGION')       
A            MAPDCD         8  0       COLHDG('PRODUCT CODE') 

MAITCL,MAITCD,	MADESC,	MALEN,	MACSCD,	MACSNM,	MADOCT,	MADOCN	,MADODT,MAORDT,	MARQDT,	MADLNO,	MADLDT,	MAORDT,	MAORDN,	MAQTY,	MAUPRC,	MAAMT,	MAPROF,
MAUCST,MATCST,	MAWGHT,	MATWGH,	MAPCEX,	MACSTP,	MARGN,	MAPDCD
